[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts",
"@solmate/=lib/solmate/src/"]
via_ir = true         
optimizer = true       
optimizer_runs = 200   
fs_permissions = [
  { access = "read", path = "./broadcast" }
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
